---
- name: Installing Apache
  apt:
    name:
    - apache2
    - pigz
    state: present

- name: moving vhost template
  template:
    src: templates/vhost.j2
    dest: "/etc/apache2/sites-available/{{ _domain }}.conf"
    owner: root
    group: root
    mode: 0644

- name: symlinking our vhost
  file:
    src: "/etc/apache2/sites-available/{{ _domain }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ _domain }}.conf"
    owner: root
    group: root
    mode: 0644
    state: link

- name: disable apache default site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: start apache2