---
- name: Installing Apache
  apt:
    name:
    - apache2
    - pigz
    state: present

- name: Enable Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - rewrite
    - headers
    - ssl
    - socache_shmcb
    - php8.3
  notify: restart apache

- name: Configure Apache virtual host
  template:
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ _domain }}.conf
    owner: root
    group: root
    mode: '0644'

- name: Disable default Apache site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache

- name: Enable FileCloud site
  file:
    src: /etc/apache2/sites-available/{{ _domain }}.conf
    dest: /etc/apache2/sites-enabled/{{ _domain }}.conf
    state: link
  notify: restart apache