---
- name: Installing PHP 8.3 and dependencies
  apt:
    name:
    - php8.3
    - php8.3-bcmath 
    - php8.3-cli 
    - php8.3-igbinary 
    - php8.3-common 
    - php8.3-curl 
    - php8.3-gd 
    - php8.3-gmp 
    - php8.3-imap 
    - php8.3-intl 
    - php8.3-ldap 
    - php8.3-mbstring 
    - php8.3-memcache 
    - php8.3-memcached 
    - php8.3-mongodb 
    - php8.3-opcache 
    - php8.3-readline 
    - php8.3-soap 
    - php8.3-xml 
    - php8.3-xsl 
    - php8.3-zip 
    - php8.3-sqlite3 
    - php-json 
    - libapache2-mod-security2